version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1492753389
layout:
  /header/:
    -
      - 'logo-4082 30'
      - 'spacer-1881 70'
  /main/:
    -
      - system-messages-1616
    -
      - system-content-7953
  /footer/:
    -
      - position-footer
    -
      - 'copyright-6165 40'
      - 'spacer-4274 30'
      - 'branding-7432 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
