name: 19
timestamp: 1494010564
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1492753493
positions:
  aside: Aside
  sidebar: Sidebar
  zero: 'Module Position'
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-5739: 'Logo / Image'
  social:
    social-1634: Social
  menu:
    menu-6317: Menu
  position:
    position-position-5870: Aside
    position-position-5151: Sidebar
    position-position-1945: 'Module Position'
  content:
    system-content-3631: 'Page Content'
  copyright:
    copyright-6592: Copyright
  totop:
    totop-1681: 'To Top'
  mobile-menu:
    mobile-menu-7019: Mobile-menu
inherit:
  default:
    navigation: navigation
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    mainbar: mainbar
    sidebar: sidebar
    footer: footer
    offcanvas: offcanvas
    logo-5739: logo-8556
    social-1634: social-3171
    menu-6317: menu-6409
    position-position-5870: position-position-4734
    system-content-3631: system-content-1587
    position-position-5151: position-position-3949
    copyright-6592: copyright-1736
    position-position-1945: position-position-9870
    totop-1681: totop-8670
    mobile-menu-7019: mobile-menu-5697
