preset: preset6
base:
  text-color: '#000000'
navigation:
  background: '#ffffff'
  text-color: '#000000'
header:
  background-image: 'gantry-media://header/food.jpg'
testimonials:
  background: ''
footer:
  background: 'rgba(92, 92, 92, 0.62)'
