name: _error
timestamp: 1493398455
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1492754428
positions:
  aside: Aside
  sidebar: Sidebar
  menu: 'Module Position'
sections:
  top: Top
  slideshow: Slideshow
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  blog: Blog
  bottom: Bottom
  clients: Clients
  above-footer: Above-footer
  fixedside: Fixedside
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-position-3568: Aside
    position-position-7414: Sidebar
    position-position-2430: 'Module Position'
  content:
    system-content-4814: 'Page Content'
  logo:
    logo-9799: 'Logo / Image'
  menu:
    menu-2200: Menu
  social:
    social-5166: Social
  copyright:
    copyright-3647: Copyright
  totop:
    totop-5124: 'To Top'
  mobile-menu:
    mobile-menu-7781: Mobile-menu
inherit:
  default:
    top: top
    slideshow: slideshow
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    blog: blog
    aside: aside
    mainbar: mainbar
    sidebar: sidebar
    bottom: bottom
    clients: clients
    above-footer: above-footer
    fixedside: fixedside
    footer: footer
    offcanvas: offcanvas
    position-position-3568: position-position-4734
    system-content-4814: system-content-1587
    position-position-7414: position-position-3949
    logo-9799: logo-2325
    menu-2200: menu-4072
    social-5166: social-4741
    position-position-2430: position-position-4739
    copyright-3647: copyright-1736
    totop-5124: totop-8670
    mobile-menu-7781: mobile-menu-5697
