css:
  -
    location: ''
    inline: ".g-menu-item-title {\nfont-size: 25px;\n}\n\n#g-navigation .g-grid{\npadding:0px;\n}\n\n\n\n\n.g-toplevel{\nmargin-top:100px;\n}"
    extra: {  }
    priority: '0'
    name: 'New item'
