version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1493312167
layout:
  /navigation/:
    -
      - 'logo-9608 20'
      - 'menu-6409 64.9'
      - 'social-9950 15'
  /header/: {  }
  /intro/: {  }
  /features/: {  }
  /utility/: {  }
  /above/: {  }
  /testimonials/:
    -
      - custom-2317
  /expanded/: {  }
  /container-main/:
    -
      -
        'aside 25':
          -
            - position-position-4734
      -
        'mainbar 50':
          -
            - system-content-1587
      -
        'sidebar 25':
          -
            - position-position-3949
  /footer/:
    -
      - 'copyright-1736 33.3'
      - 'social-3171 33.3'
      - 'totop-8670 33.3'
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: '2'
      class: ''
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  aside:
    attributes:
      class: ''
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  logo-9608:
    title: 'Logo / Image'
    attributes:
      image: 'gantry-media://horest.png'
  menu-6409:
    attributes:
      menu: mainmenu
      base: /
      startLevel: '1'
      maxLevels: '0'
      renderTitles: '0'
      hoverExpand: '1'
      mobileTarget: '0'
  social-9950:
    attributes:
      target: _blank
      display: both
      items:
        -
          icon: 'fa fa-twitter fa-fw'
          text: ''
          link: 'https://twitter.com/likornet'
          name: Twitter
        -
          icon: 'fa fa-facebook fa-fw'
          text: ''
          link: 'https://www.facebook.com/dinara.tusupova.9'
          name: Facebook
        -
          icon: 'fa fa-google-plus fa-fw'
          text: ''
          link: 'https://plus.google.com/u/0/'
          name: Google+
  custom-2317:
    title: 'Custom HTML'
    attributes:
      html: "<div id=\"new-places\">\n<h1 style=\"text-align: center; margin-top:0px;\"> 5 новых модных заведений Алматы </h1>\n<div class=\"fp-features\">\n    <div class=\"g-grid\">\n         <div class=\"g-block size-45\" style=\"margin-right: 25px;\">\n            <div class=\"card\">\n                <div class=\"card-block\">\n                    <img src=\"images/pinch.JPG\" alt=\"Pinch\" style=\"border-radius: 8px;\"/>\n<h4 class=\"card-title\">Pinch</h4>\n                    <p class=\"card-text\">Бар Pinch – первое заведение ресторанной группы Vesna Group, которая только заходит в Казахстан. Хозяева описывают его как гастробар, хотя Pinch запросто может претендовать на звание качественного коктейльного бара. Специально для подготовки персонала приезжали питерские бармены, которые составили богатую и интересную коктейльную карту, где каждый найдет \"свой\" напиток.</p>\n\n                </div>\n            </div>\n        </div>\n        <div class=\"g-block size-45\">\n            <div class=\"card\">\n                <div class=\"card-block\">\n                   <img src=\"images/smug.jpg\" alt=\"Smug\" style=\"border-radius: 8px;\" /> \n                    <h4 class=\"card-title\">Smug Burger</h4>\n                    <p class=\"card-text\">Новое место на карте города — бургерная  с баром: к большим и вкусным бургерам здесь подают крафтовое пиво, вино и фирменные коктейли. Меню заведения включает в себя четыре авторских бургера: с куриным филе и маринованными яблоками, пастрами, блючиз и вишня в стауте — вишневая булочка, копченая конина (жая) и вишня, которая вываривается в нефильтрованном пиве.\n\nЕсли вы любитель экспериментов, то вам предложат собрать свой бургер, подобрав булочку, котлету и соус. А вместо привычной картошки фри, здесь готовят сладкий батат во фритюре.</p>\n                </div>\n            </div>\n        </div>\n        \n            </div>\n        \n\n <div class=\"g-grid\">\n<div class=\"g-block size-45\" style=\"margin-right: 25px;\" >\n            <div class=\"card\">\n                <div class=\"card-block\">\n                    <img src=\"images/falafel.jpg\" alt=\"Falafel\" style=\"border-radius: 8px;\" /> \n                    <h4 class=\"card-title\">Falafel Forever</h4>\n                    <p class=\"card-text\">Фалафель — это один из самых распространенных в мире видов уличной еды. Он готовится из отварного нута и специй, обжаренный во фритюле или запеченный в духовке.\n\nВ Falafel Forever главное блюдо подают в пите с овощами и заправками — на выбор три разных хумуса. Один из фаворитов посетителей фалафель «Гурмэ» — соус тахини, неочищенные конопляные семечки, пищевые вегетарианские дрожжи и авторские специи. Как видите, данное заведение для любителей здоровой и вкусной пищи.</p>\n                </div>\n            </div>\n        </div>\n<div class=\"g-block size-45\">\n            <div class=\"card\">\n                <div class=\"card-block\">\n                    <img src=\"images/butler.jpg\" alt=\"Butler TeaRoom\" style=\"border-radius: 8px;\"/>\n<h4 class=\"card-title\">Butler Tearoom</h4>\n                    <p class=\"card-text\">Приятный интерьер, красивая посуда и отменный выбор чая — новое место для любителей уютных посиделок и вкусных воскресных бранчей. А также для всех тех, кто ищет приветливый сервис и необычные сеты завтраков.</p>\n\n                </div>\n            </div>\n        </div>\n</div>\n<div class=\"g-grid\">\n        <div class=\"g-block size-45\">\n            <div class=\"card\">\n                <div class=\"card-block\">\n                   <img src=\"images/gantry/daily_coffee-8588-14_ru-min.jpg\" alt=\"Daily Coffee\" style=\"border-radius: 8px;\" /> \n                    <h4 class=\"card-title\">Daily Coffee</h4>\n                    <p class=\"card-text\">Кафе с уютной атмосферой, теплым антуражем и приветливым персоналом. Гостей порадуют разнообразные блюда европейской кухни и демократичные цены.</p>\n                </div>\n       </div>\n</div>\n        <div class=\"g-block size-50\" >\n            <div class=\"card\">\n                <div class=\"card-block\">\n                </div>\n            </div>\n        </div>\n    </div>\n</div>\n</div>\n"
  position-position-4734:
    title: Aside
    attributes:
      key: aside
  position-position-3949:
    title: Sidebar
    attributes:
      key: sidebar
  social-3171:
    block:
      class: g-social-header
  totop-8670:
    title: 'To Top'
