preset: preset6
navigation:
  background: '#ffffff'
  text-color: '#000000'
intro:
  background: '#423535'
  text-color: '#ffffff'
features:
  background: ''
utility:
  background: ''
above:
  background: ''
testimonials:
  background: '#6b6060'
  background-image: 'gantry-media://ground.jpg'
  background-overlay: disabled
  text-color: '#203645'
expanded:
  background: ''
footer:
  background: 'rgba(92, 92, 92, 0.62)'
  text-color: '#ffffff'
offcanvas:
  background: ''
