name: 10
timestamp: 1493312173
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1493312173
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-5113: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-4321: Menu
  messages:
    system-messages-4832: 'System Messages'
  content:
    system-content-5820: 'Page Content'
  copyright:
    copyright-4476: Copyright
  spacer:
    spacer-9193: Spacer
  branding:
    branding-3154: Branding
  mobile-menu:
    mobile-menu-4138: Mobile-menu
inherit: {  }
